//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int userId { get; set; }
        public string adminId { get; set; }
        public string adminName { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
    }
}
