//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public string courseId { get; set; }
        public string courseName { get; set; }
        public string lecturerName { get; set; }
        public string day { get; set; }
        public string time { get; set; }
        public string location { get; set; }
    }
}
