//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public long studentId { get; set; }
        public Nullable<int> userId { get; set; }
        public string studentName { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string major { get; set; }
        public DateTime dateofbirth { get; set; }
    
        public virtual user user { get; set; }

        public string FormattedDateOfBirth
        {
            get { return dateofbirth.ToString("d/MM/yyyy"); }
        }
    }
}
